(define (domain the_three_towers)
  (:requirements :strips)
  (:predicates
    (on_tower1 ?x ?y)
    (on_tower2 ?x ?y)
    (on_tower3 ?x ?y)
    (on_top ?x)
    (hand_empty)
    (hand_holding ?x)
  )
  (:action take_from_tower1
    :parameters(?x ?y)
    :precondition (and (on_tower1 ?x ?y)
                       (on_top ?x)
                       (hand_empty))
    :effect (and (not (hand_empty)) 
                 (hand_holding ?x) 
                 (not (on_top ?x)) 
                 (on_top ?y)
                 (not (on_tower1 ?x ?y)))
  )
  (:action put_on_tower1
    :parameters(?x ?y)
    :precondition (and (not (hand_empty))
                       (hand_holding ?x)
                       (on_top ?y))
    :effect (and (hand_empty)
                 (not (hand_holding ?x))
                 (not (on_top ?y))
                 (on_top ?x)
                 (on_tower1 ?x ?y))
  )
  (:action take_from_tower2
    :parameters(?x ?y)
    :precondition (and (on_tower2 ?x ?y)
                       (on_top ?x)
                       (hand_empty))
    :effect (and (not (hand_empty)) 
                 (hand_holding ?x) 
                 (not (on_top ?x)) 
                 (on_top ?y)
                 (not (on_tower2 ?x ?y)))
  )
  (:action put_on_tower2
    :parameters(?x ?y)
    :precondition (and (not (hand_empty))
                       (hand_holding ?x)
                       (on_top ?y))
    :effect (and (hand_empty)
                 (not (hand_holding ?x))
                 (not (on_top ?y))
                 (on_top ?x)
                 (on_tower2 ?x ?y))
  )
  (:action take_from_tower3
    :parameters(?x ?y)
    :precondition (and (on_tower3 ?x ?y)
                       (on_top ?x)
                       (hand_empty))
    :effect (and (not (hand_empty)) 
                 (hand_holding ?x) 
                 (not (on_top ?x)) 
                 (on_top ?y)
                 (not (on_tower3 ?x ?y)))
  )
  (:action put_on_tower1
    :parameters(?x ?y)
    :precondition (and (not (hand_empty))
                       (hand_holding ?x)
                       (on_top ?y))
    :effect (and (hand_empty)
                 (not (hand_holding ?x))
                 (not (on_top ?y))
                 (on_top ?x)
                 (on_tower3 ?x ?y))
  )
)
