(define (problem save_energy)
  (:domain lighting)
  (:objects l1 l2)
  (:goal (and (or (and (light_on l1) (not (sun_light l1)))
                  (and (sun_light l1) (not (light_on l1))))
              (or (and (light_on l2) (not (sun_light l2)))
                  (and (sun_light l2) (not (light_on l2))))))
)
