(define (problem low_standing_sun)
  (:domain lighting)
  (:objects l1 l2)
  (:init (light_on l1) 
         (not (light_on l2))
         (sun_light l1)
         (not (sun_light l2)))
  (:goal (and (or (and (light_on l1) (not (sun_light l1)))
                  (and (sun_light l1) (not (light_on l1))))
              (or (and (light_on l2) (not (sun_light l2)))
                  (and (sun_light l2) (not (light_on l2))))))
)
