(define (problem sorted_tower)
  (:domain the_three_towers)
  (:objects a b c d e f g h)
  (:init (hand_empty) 
         (on_top a) 
         (on_tower1 a b) 
         (on_tower1 b c) 
         (on_tower1 d e) 
         (on_top f) 
         (on_tower3 f g)
         (on_tower3 g h))
  (:goal (and (hand_empty)
              (on_top a)
              (on_tower1 a b) 
              (on_tower1 b c)
              (on_tower1 c d)
              (on_tower1 e f)
              (on_tower1 g h)))
)
